parserOptions:
    ecmaVersion: 8
    sourceType: 'module'
    ecmaFeatures:
        jsx: true
        impliedStrict: true
env: { node: true }
globals: { CONFIG: true, ENV: true, TEST: true, es6: true, Promise: true }
extends: "eslint:recommended"
rules:
    indent:
        - error
        - 2
    semi: error
    no-const-assign: error
    no-var: error
    prefer-const: error
    prefer-destructuring: ["warn", {"object": true, "array": false}]
    no-redeclare: error
    camelcase: warn
    no-magic-numbers: warn
    global-require: error
    curly: error
    brace-style:
        - error
        - stroustrup
    object-curly-newline: ["warn", { "multiline": true }]
    object-curly-spacing:
        - error
        - always
    no-template-curly-in-string: error
    # func-style:
    #   - error
    #   - expression
    new-parens: error
    space-in-parens:
        - warn
        - never
    arrow-parens:
        - error
        - always
    space-before-function-paren: warn
    arrow-body-style: ["error", "as-needed", { "requireReturnForObjectLiteral": true }]
    no-useless-constructor: error
    new-cap: error
    no-multi-spaces: error
    no-mixed-spaces-and-tabs: error
    no-trailing-spaces: error
    quotes:
        - error
        - single
    eqeqeq:
        - error
        - smart
    dot-location:
        - error
        - property
    no-multiple-empty-lines: ["error", { "max": 2}]
    operator-linebreak:
        - error
        - after
    spaced-comment:
        - warn
        - always
    generator-star-spacing: ["error", {"before": false, "after": true}]
    prefer-promise-reject-errors: warn
    handle-callback-err: error
    key-spacing: error
    arrow-spacing: error
    block-spacing: error
    array-bracket-spacing: error
    array-bracket-newline: error
    space-before-blocks: error
    padding-line-between-statements: [
        "error",
        { "blankLine": "always", "prev": "*", "next": "return" },
        { "blankLine": "always", "prev": "*", "next": "if" }
    ]
    keyword-spacing: [ "error",
                       { "overrides": {
                           "if": { "after": false },
                           "while": { "after": false }
                       }
                       }]
    no-console: off